"""empty message

Revision ID: 7d378e8af1c3
Revises: c17a24e9896d
Create Date: 2026-01-09 14:18:15.744251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d378e8af1c3'
down_revision = 'c17a24e9896d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('followerid', sa.Integer(), nullable=False),
    sa.Column('followedid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['followedid'], ['user.id'], ),
    sa.ForeignKeyConstraint(['followerid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
